spring:
  datasource:
    url: jdbc:mysql://82.156.189.178:33306/EShop
    username: root
    password: We9654rt
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/vapor/eshop/mapper/xml/*.xml

server:
  port: 9090
